resolver: lts-7.4

packages:
- '.'

extra-deps:
- optparse-applicative-0.12.1.0
- distributed-process-0.6.6
- distributed-process-simplelocalnet-0.2.3.3
- network-multicast-0.1.2
- network-transport-tcp-0.5.1
- network-transport-inmemory-0.5.1
- tasty-0.11.0.4
- tasty-quickcheck-0.8.4
- tasty-hunit-0.9.2
- QuickCheck-2.9.2
- HUnit-1.5.0.0

flags: {}

extra-package-dbs: []
